### ISSUE TITLE
axios post response is undefined for react-native

### ISSUE THREAD

**Issue by busrakarausta** [busrakarausta/ceng396-software-engineering#4]
I have used axios post to fetch the data in react-native but response is undefined. Sometimes it cant catch the error but it can be caused by my backend code.

I tried http and https but this didn't work or it doesnt working with or without header. Is there anyone to find the mistake on my code?

` axios
      .post(
        "http://192.168.1.34:3000/auth/",
        {
          email: email,
          password: password
        },
        {
          headers: { "Content-Type": "application/json" }
        }
      )
      .then(response => {
        console.log(response);
        console.log(email);
      })
      .catch(error => {
        console.log("loginAction:", error);
      });`

**Comment by elifsoolmaz** [comment]
First thing I'd do is check CORS for your POST request.
I found a solution on this page;  https://stackoverflow.com/a/56309583 .
